Added server side error catching examples to docs
VeliovGroup/Meteor-logger pull request #7
Opened 2017-08-17 20:32 UTC by fawzisf

2017-08-18 17:21 UTC, dr-dimitru commented on README.md
> +//store original Meteor error
add one space after `//`

2017-08-18 17:23 UTC, dr-dimitru requested changes

2017-08-18 17:23 UTC, dr-dimitru commented on README.md
> +let originalMeteorDebug = Meteor._debug;
We can safely use `const` here

2017-08-18 17:23 UTC, dr-dimitru commented on README.md
> +  let error = new Error(message);
`const` will work here too

2017-08-18 17:24 UTC, dr-dimitru commented
Everything looks great to me, I've requested minor changes.

Will you be able add same code snippets to?:
 - [File](https://atmospherejs.com/ostrio/loggerfile);
 - [Mongo](https://atmospherejs.com/ostrio/loggermongo);
 - [Console](https://atmospherejs.com/ostrio/loggerconsole).

2017-08-18 19:08 UTC, fawzisf commented
@dr-dimitru sure !

_Sent from my Samsung SM-N920C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-19 15:04 UTC, dr-dimitru approved these changes

2017-08-19 15:04 UTC, merged

2017-08-19 15:05 UTC, dr-dimitru commented
@fawzisf thanks a lot, merged.